spring:
  application:
    name: noticeboard-service

# Mapper Xml Location
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.noticeboardservice.dto # Dto 매핑 클래스 패키지 지정
  configuration:
    map-underscore-to-camel-case: true

# 카카오 REST API KEY
kakao-rest-api-key: 049c84589ed98d01f5fe19b15cb67ea4

---
spring:
  config:
    activate:
      on-profile: local # 환경이름설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/noticeboard?serverTimezone=UTC
    username: root
    password: 1234

# 이미지 경로 설정
upload-path: file:///C:/images/
default-img-path: classpath:/static/default-image/
member-img-location: C:/images/member
product-img-location: C:/images/product
category-img-location: C:/images/category

---
spring:
  config:
    activate:
      on-profile: dev # 환경이름설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://mysql-app:3306/noticeboard?serverTimezone=UTC # 컨테이너 sql 서비스명
    username: root
    password: 1234

upload-path: file:/app/images/
default-img-path: classpath:/static/default-image/
member-img-location: /app/images/member
product-img-location: /app/images/product
category-img-location: /app/images/category

---
spring:
  config:
    activate:
      on-profile: test # 환경이름설정
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/testboard?serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/testboard?serverTimezone=UTC
    username: root
    password: 1234