server:
  port: 8081

spring:
  application:
    name: noticeboard-admin
  # MySQL DataSource
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/noticeboard?serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/noticeboard?serverTimezone=UTC
    username: root
    password: 1234

# Mapper Xml Location
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.limnj.noticeboardadmin.category, com.limnj.noticeboardadmin.image
  configuration:
    map-underscore-to-camel-case: true

# 이미지 경로 설정
uploadPath: file:///C:/images/
defaultImgPath: classpath:/static/default-image/
categoryImgLocation: C:/images/category

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/testboard?serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/testboard?serverTimezone=UTC
    username: root
    password: 1234