# Stage 1: Build JAR using gradle
FROM gradle:7.6.1-jdk17 AS builder
WORKDIR /app
COPY backend /app/backend
WORKDIR /app/backend
RUN ./gradlew clean build -x test

# Stage 2: Run JAR
FROM openjdk:17-jdk
WORKDIR /app
COPY --from=builder /app/backend/build/libs/noticeboard-service-0.0.1-SNAPSHOT.jar spring-app.jar
EXPOSE 8080
ENTRYPOINT ["/bin/sh", "-c", "java -jar /app/spring-app.jar > /app/logs/nohup.log 2>&1"]