version: '3.8'

services:
  jenkins:
    build:
      context: . # Dockerfile이 있는 위치
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - TZ=Asia/Seoul

volumes:
  jenkins_home:
