# Stage 2: Run JAR
FROM openjdk:17-jdk
WORKDIR /app
COPY backend/build/libs/noticeboard-service-0.0.1-SNAPSHOT.jar spring-app.jar

EXPOSE 8080
ENTRYPOINT ["/bin/sh", "-c", "java -jar /app/spring-app.jar"]